[build]
  # أخبره بمكان المشروع
  base = "frontend"

  # أمر البناء
  command = "npm run build"

  # مكان المجلد النهائي
  publish = "frontend/build" # أو "frontend/dist"

  [build.environment]
    NODE_VERSION = "18.18.2"

[[plugins]]
  package = ""
```    *   **أهم تعديل:** أضفنا `base = "frontend"` لنخبره صراحةً بمكان مشروع الـ React.